# Generated by Django 3.1.4 on 2022-05-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220510_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatartwo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
