# Generated by Django 3.1.4 on 2022-05-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20220510_1106'),
        ('posts', '0008_auto_20220510_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatartwo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
