# Generated by Django 3.1.4 on 2022-05-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220510_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='avatartwo',
        ),
    ]
