# Generated by Django 3.1.4 on 2022-05-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20220510_1106'),
        ('posts', '0010_remove_post_avatartwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatartwo',
            field=models.ManyToManyField(blank=True, related_name='profile', to='profiles.Profile'),
        ),
    ]
