# Generated by Django 3.1.4 on 2022-05-08 16:21

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220508_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=django_fields.fields.DefaultStaticImageField(upload_to=''),
        ),
    ]
