# Generated by Django 3.1.4 on 2022-05-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20220508_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='blog/media/default.jpg', upload_to='blog/media/profile_images'),
        ),
    ]
